theme: jekyll-theme-midnight

title: Pop Together
description: Watch anything, anywhere with anyone you like! Laugh together and avoid spoilers by synchronizing your screen easily.

show_downloads: false
google_analytics: null